##################################################
# General
##################################################
env:
  IMAGE_NAME: uupascal/rest-light


##################################################
# On Dev
##################################################
on:
  push:
    branches:
      - dev

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2

        - name: Login to DockerHub
          run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

        - name: Get the commit hash
          id: hash
          run: echo ::set-output name=tag::$(echo ${GITHUB_SHA:7})

        - name: Get current date
          id: date
          run: echo "::set-output name=date::$(date +'%Y.%m.%d')"

        - name: Build the tagged Docker image
          run: docker build . --file Dockerfile --tag "${IMAGE_NAME}:${{ steps.hash.outputs.tag }}" --tag "$IMAGE_NAME:DEV-${{ steps.date.outputs.date }}" --tag "$IMAGE_NAME:DEV-latest"

        - name: Push the tagged Docker image
          run: docker push "${IMAGE_NAME}:latest"

