##################################################
# General
##################################################
env:
  IMAGE_NAME: uupascal/rest-light


##################################################
# On Dev
##################################################
on:
  push:
    branches:
      - dev

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
        - name: Checkout project
          uses: actions/checkout@v2

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v1

        - name: Set up Docker Buildx
          id: buildx
          uses: docker/setup-buildx-action@v1

        - name: Login to DockerHub
          run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

        - name: Get current date
          id: date
          run: echo "::set-output name=date::$(date +'%Y.%m.%d')"

        - name: Pull image to leverage cache
          run: docker pull "$IMAGE_NAME:DEV-latest" || true

        - name: Build the tagged Docker image for raspberry pi
          run: > 
            docker buildx build 
            --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6 
            --file Dockerfile 
            --push
            --build-arg APP_VERSION="DEV-${{ steps.date.outputs.date }}"
            --build-arg GITHUB_REPOSITORY
            --build-arg "CLONE_COMMAND_WIRING_PI=git clone --recursive -b final_official_2.50 https://github.com/WiringPi/WiringPi.git /opt/wiringPi"
            --tag "$IMAGE_NAME:DEV-${{ steps.date.outputs.date }}" 
            --tag "$IMAGE_NAME:DEV-${{ steps.date.outputs.date }}-rpi" 
            --tag "$IMAGE_NAME:DEV-latest-rpi"
            --tag "$IMAGE_NAME:DEV-latest" .

        - name: Build the tagged Docker image for bananpi pi
          run: > 
            docker buildx build 
            --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6 
            --file Dockerfile 
            --push
            --build-arg APP_VERSION="DEV-${{ steps.date.outputs.date }}"
            --build-arg GITHUB_REPOSITORY
            --build-arg "CLONE_COMMAND_WIRING_PI=git clone --recursive https://github.com/BPI-SINOVOIP/BPI-WiringPi2 /opt/wiringPi"
            --tag "$IMAGE_NAME:DEV-${{ steps.date.outputs.date }}" 
            --tag "$IMAGE_NAME:DEV-${{ steps.date.outputs.date }}-bpi" 
            --tag "$IMAGE_NAME:DEV-latest-bpi"
            --tag "$IMAGE_NAME:DEV-latest" .
