##################################################
# General
##################################################
env:
  IMAGE_NAME: uupascal/rest-light


##################################################
# On Release
##################################################
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - '.github/**'
      - '.doc/**'

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
        - name: Checkout project
          uses: actions/checkout@v2

        - name: Get current date
          id: date
          run: echo "::set-output name=date::$(date +'%Y.%m.%d-%H%M')"

        - name: Create Release
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          with:
            tag_name: ${{ steps.date.outputs.date }}
            release_name: ${{ steps.date.outputs.date }}
            body: "Automatically created release for push in main: ${{ github.event.head_commit.message }}"
            prerelease: true

        - name: Update Docker Hub Description
          uses: peter-evans/dockerhub-description@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_DESC_PASSWORD }}
            repository: ${{ env.IMAGE_NAME }}
            short-description: ${{ github.event.repository.description }}

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v1

        - name: Set up Docker Buildx
          id: buildx
          uses: docker/setup-buildx-action@v1

        - name: Login to DockerHub
          run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

        - name: Pull image to leverage cache
          run: docker pull "$IMAGE_NAME:latest"

        - name: Build the tagged Docker image
          run: > 
            docker buildx build 
            --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6 
            --file Dockerfile 
            --push
            --build-arg APP_VERSION="${{ steps.date.outputs.date }}"
            --build-arg GITHUB_REPOSITORY
            --tag "$IMAGE_NAME:${{ steps.date.outputs.date }}" 
            --tag "$IMAGE_NAME:latest" .
